name: event_ease
description: "A new Flutter project."
# Flutter 3.22.2

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  firebase_core: ^3.10.0
  get: ^4.6.6
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.0
  google_nav_bar: ^5.0.7
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.1
  file_picker: ^8.1.7
  image_picker: ^1.1.2
  skeletonizer: ^1.4.3
  carousel_slider: ^5.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  table_calendar: ^3.2.0
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.1
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
